- src/gobstuf/mks_utils.py
- src/gobstuf/rest/README.md
- src/gobstuf/rest/brp/base_view.py
- src/gobstuf/stuf/brp/base_request.py
- src/gobstuf/stuf/brp/base_response.py
- src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
- src/gobstuf/stuf/brp/request_template/ingeschrevenpersonen.xml
- src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
- src/gobstuf/stuf/message.py
- src/tests/rest/brp/request/test_ingeschrevenpersonen.py
- src/tests/rest/brp/response/test_ingeschrevenpersonen.py
- src/tests/rest/brp/test_base_view.py
- src/tests/stuf/brp/test_base_request.py
- src/tests/stuf/brp/test_base_response.py
- src/tests/test_api.py
- src/tests/test_mks_utils.py
Add basis persoonsgegevens to the ingeschrevenpersonen request
Made the implementation conform the Haal-Centraal API
- Check the BSN parameter for validity
- Remove None values from the result
- Return json data on any errors (no HAL)
Filtered out overleden personen conform specification in the ticket
> PGB-928 Basis Persoonsgegevens

- src/gobstuf/rest/brp/base_view.py
- src/gobstuf/rest/brp/rest_response.py
- src/requirements.txt
- src/tests/rest/brp/test_base_view.py
- src/tests/rest/brp/test_rest_response.py
OK responses are in HAL-JSON format
Error responses are guaranteed to contain all required fields
The data is returned in problem-JSON format
> RESTResponse class to handle all REST responses

- src/gobstuf/lib/communicatie.py
- src/gobstuf/mks_utils.py
- src/tests/lib/test_communicatie.py
- src/tests/test_mks_utils.py
Determines aanhef and aanschrijfwijze voor personen
> Communication library

- src/gobstuf/mks_utils.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_response_mapping.py
- src/tests/test_mks_utils.py
If a person has died then include a formatted overlijden
part in the response
> Format overlijden

- src/gobstuf/indications.py
- src/gobstuf/lib/communicatie.py
- src/gobstuf/mks_utils.py
- src/gobstuf/stuf/brp/base_response.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_base_response.py
- src/tests/test_mks_utils.py
Made get_mapped_object a little bit smarter by having it resolve arrays.
Behavioral tests have been added for get_mapped_object to better explain and test its behaviour
> PGB 1244 vervolg

- src/gobstuf/lib/communicatie.py
- src/gobstuf/stuf/brp/response_mapping.py
Convert datum begin- and and huwelijkPartnership
to datum struct.
> Fix aanhef and aanschrijfwijze

- src/gobstuf/lib/communicatie.py
- src/gobstuf/stuf/brp/response_mapping.py
Convert datum begin- and and huwelijkPartnership
to datum struct.
> Release Fix aanhef and aanschrijfwijze

- src/Dockerfile.test
- src/gobstuf/api.py
- src/gobstuf/audit_log.py
- src/gobstuf/config.py
- src/requirements.txt
- src/tests/test_api.py
- src/tests/test_audit_log.py
To log all requests and responses from the StUF API
> Use AuditLogger middleware

- src/Dockerfile.test
- src/gobstuf/api.py
- src/gobstuf/audit_log.py
- src/gobstuf/config.py
- src/requirements.txt
- src/tests/test_api.py
- src/tests/test_audit_log.py
To log all requests and responses from the StUF API
> Release AuditLogger middleware

- src/gobstuf/audit_log.py
- src/tests/test_audit_log.py
No request/response should remain unlogged.
If for any reason the logging should fail
an error message and the request/response data
is printed on stdout
> Auditlog to stdout when auditlog fails

- src/gobstuf/audit_log.py
- src/tests/test_audit_log.py
No request/response should remain unlogged.
If for any reason the logging should fail
an error message and the request/response data
is printed on stdout
> Release auditlog to stdout when auditlog fails

- src/gobstuf/stuf/brp/base_response.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_base_response.py
- src/tests/stuf/brp/test_response_mapping.py
- Embedded properties get shown in links, even if they are not expanded
- Links to embedded properties now direct to the detail page
> Fix acceptance issues

- src/gobstuf/rest/brp/argument_checks.py
- src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
- src/tests/rest/brp/test_argument_checks.py
- src/tests/stuf/brp/request/test_ingeschrevenpersonen.py
Value should be 4 characters and present in the gemeente table
> Gemeente can now be searched on code instead of omschrijving

- docker-compose.yml
- src/Dockerfile
- src/deploy/docker-run.sh
- src/gatekeeper.conf
- src/gobstuf/api.py
- src/gobstuf/auth/routes.py
- src/gobstuf/config.py
- src/gobstuf/rest/brp/base_view.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/auth/test_auth.py
- src/tests/rest/brp/test_base_view.py
- src/tests/stuf/brp/test_response_mapping.py
An insecure endpoint is added to allow testing with the current MKS headers
> Add gatekeeper and accept auth headers

- src/gobstuf/rest/brp/argument_checks.py
- src/gobstuf/rest/brp/base_view.py
- src/gobstuf/stuf/brp/base_response.py
- src/tests/rest/brp/test_argument_checks.py
- src/tests/rest/brp/test_base_view.py
- src/tests/stuf/brp/test_base_response.py
Dong?? wasn't returning the correct results, also added a new testcase
> Fix issue with wilcard query

- src/gobstuf/indications.py
- src/gobstuf/mks_utils.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_response_mapping.py
- src/tests/test_mks_utils.py
Filter out None values on lists in response mapping, ignored the too complex message for readability
> Add aanduiding to nationaliteit

- src/gobstuf/rest/brp/rest_response.py
- src/requirements.txt
Only some constants were used from this package and this was causing build failures
> Remove Flask-API from requirements

- .gitignore
- src/oauth2-proxy.cfg
Allows multiple domains and adds more logging.
> Add debug values to oauth2-proxy.cfg

- src/gobstuf/regression_tests/brp.py
- src/tests/regression_tests/test_brp.py
Inside the regression test json for the expected values, you can replace certain predefined variables.
> Add JSONDecoder to replace values

- src/gobstuf/stuf/brp/response_mapping.py
Reordered attributes as 'Haal Centraal' specifies them.
> reorder_attributes

- src/gobstuf/auth/routes.py
- src/requirements.txt
- src/tests/auth/test_auth.py
- src/tests/conftest.py
- src/tests/rest/brp/test_views.py
> Disallow access when brp_r role not available

- Jenkinsfile
- src/.jenkins/test/docker-compose.yml
- src/gobstuf/api.py
- src/gobstuf/auth/routes.py
- src/gobstuf/blueprints/__init__.py
- src/gobstuf/blueprints/hc.py
- src/gobstuf/blueprints/secure.py
- src/gobstuf/config.py
- src/gobstuf/rest/routes.py
- src/tests/auth/test_auth.py
- src/tests/conftest.py
- src/tests/pytest.ini
- src/tests/test_api.py
this allows for redirect from hc.data.amsterdam.nl to these endpoints
> Add all rest routes on base path

- src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
- src/tests/rest/brp/test_views.py
> Set max length huisnummertoevoeging arg to 4

- src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
- src/tests/rest/brp/test_views.py
* Set max length huisnummertoevoeging arg to 4
* Parameterize query param test
> Set max length huisnummertoevoeging arg to 4 (#289)

- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/fixtures/response_310.xml
- src/tests/fixtures/response_310_in_onderzoek_j.xml
- src/tests/fixtures/response_310_in_onderzoek_n.xml
- src/tests/fixtures/response_310_verblijfstitel_incomplete.xml
- src/tests/fixtures/response_310_verblijfstitel_verkrijging_aanduiding.xml
- src/tests/rest/brp/test_views.py
should get data from `a-nummer`, see https://dev.azure.com/CloudCompetenceCenter/Datateam%20Basis%20en%20Kernregistraties/_workitems/edit/28202
> Add `aNummer` mapping

- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/regression_tests/test_brp.py
- src/tests/stuf/brp/test_response_mapping.py
Take the briefadres if present, else woonadres
> Fix adres mapping

- src/gobstuf/blueprints/secure.py
- src/gobstuf/rest/brp/argument_checks.py
- src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
- src/tests/rest/brp/test_argument_checks.py
- src/tests/rest/brp/test_views.py
> Add integer validation to bsn query

- src/gobstuf/mks_utils.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/fixtures/response_310_brief_adres.xml
- src/tests/rest/brp/test_views.py
- src/tests/test_mks_utils.py
> Use different path for datumAanvangAdreshouding

- src/gobstuf/rest/brp/views.py
- src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
- src/tests/rest/brp/test_views.py
Also added test cases for all filter parameters.
> 28016: Filter ingeschrevenpersonen by nummeraanduiding

- README.md
- docker-compose.yml
- src/.jenkins/test/docker-compose.yml
- src/Dockerfile
Er moet nog naar de ontbrekende `rabbitmq.conf` uit `src/.jenkins/test/docker-compose.yml` gekeken worden.
> Migrate to GOB base and wheelhouse images

- Jenkinsfile
- README.md
- docker-compose.yml
- src/.dockerignore
- src/.jenkins/test/docker-compose.yml
- src/Dockerfile
- src/test.sh
- src/tests/pytest.ini
* Run as user datapunt.
* Testing before style checks.
> Run as user datapunt. (#311)

- src/gobstuf/regression_tests/brp.py
- src/tests/regression_tests/test_brp.py
get_object returns iterator instead of bytes
> Fix writing objectstore objects (#315)

- src/gobstuf/stuf/brp/base_response.py
- src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/rest/brp/test_views.py
- src/tests/rest/brp/test_views_historie.py
- fetch the first object
- add tests
- datumIngangGeldigheid should fallback to datumAanvangAdreshouding for the current verblijfplaats (not available in MKS)
> Fix response type verblijfplaatshistorie

- src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/fixtures/response_310_historie_overleden.xml
- src/tests/rest/brp/test_views.py
- src/tests/rest/brp/test_views_historie.py
- return datumIngangGeldigheid when available at location, no fallback
- return empty response when no verblijfplaatsen found. For example in case of indicatieoverleden
> Remove fallback for datumIngangGeldigheid

- src/gobstuf/stuf/brp/base_response.py
- src/tests/rest/brp/test_views_historie.py
- src/tests/stuf/brp/test_base_response.py
* adds request.args filtering
* fixes overcomplicated filter func
* reorganize filter functions
* change residence into verblijfplaats
Co-authored-by: geertvr <geert@DESKTOP-IDOSD2K.localdomain>
> adds request.args filtering (#336)

- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_response_mapping.py
> Return ouder if `burgerservicenummer` is present

- src/gobstuf/config.py
- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_response_mapping.py
* Add `_links` to verblijfplaats objects
* Add lig/standplaats/verblijfsobject links
* Move endpoints to config.py
* Move add_links to response_mapping.py
* return empty dict from get_links
> Add `_links` to verblijfplaats objects (#338)

- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/stuf/brp/test_response_mapping.py
[AB#66932](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/66932)
> Filter `datumAanvangAdreshouding` when person is abroad

- src/gobstuf/stuf/brp/response_mapping.py
- src/tests/fixtures/response_310_empty.xml
- src/tests/rest/brp/test_views_historie.py
- src/tests/stuf/brp/test_response_mapping.py
rebase https://github.com/Amsterdam/GOB-StUF/pull/348 ✅ 
- Add fallback for `datumIngangGeldigheid` in case of no historic verblijfplaatsen only actual
> Fix datuminganggeldigheid

- src/gobstuf/blueprints/secure.py
- src/requirements.txt
- src/tests/conftest.py
* Removed secure REST_ROUTES.
* Update Core and Config.
> Remove secure REST_ROUTES. (#358)

- src/gobstuf/app.py
- src/tests/test_app.py
* Disable regression tests
* Re-enable part of the test to hit coverage
* Remove mock for Thread
> Disable regression tests (#375)
