src/gobstuf/mks_utils.py
src/tests/test_mks_utils.py

If a value is missing then the result from zfill this value should return None

Handle zfill on None value

---

src/gobstuf/stuf/brp/request_template/ingeschrevenpersonen.xml
src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
src/tests/rest/brp/response/test_ingeschrevenpersonen.py

Choose verblijfsadres as verblijfplaats, fallbackto correspondentieadres if missing
Include aanduiding adresseerbaar object en nummeraanduiding

PGB 1237 Split woonadres/briefadres, use nummeraanduiding and adresseerbaar object

---

src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
src/gobstuf/stuf/message.py
src/tests/stuf/brp/test_base_response.py
src/tests/stuf/test_message.py

Some attributes require a filter on a collection
for example to get a value from a sublist with a certain attribute value:
```
<StUF:extraElementen>
<StUF:extraElement naam="identificatieNummerAanduiding">0363200000429356
</StUF:extraElement>
<StUF:extraElement naam="officieleStraatnaam">Overamstelstraat</StUF:extraElement>
</StUF:extraElementen>
```
The XPath expression:
-  `.//StUF:extraElement[@naam="identificatieNummerAanduiding"]`
will return the element that matches the given attribute value.

Use XPath for attribute resolution

---

src/gobstuf/rest/brp/views.py
src/gobstuf/rest/routes.py
src/gobstuf/stuf/brp/base_request.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/gobstuf/stuf/brp/request_template/ingeschrevenpersonen.xml
src/gobstuf/stuf/message.py
src/tests/rest/brp/request/test_ingeschrevenpersonen.py
src/tests/rest/brp/test_views.py
src/tests/stuf/brp/test_base_request.py
src/tests/stuf/test_message.py

Add create_elm functionality to StufMessage
Change BaseRequest implementation: Use empty XML template and add the expected paths if they don't exist yet => Makes the templates reusable for different requests.
Change naming existing Ingeschrevenpersonen views and requests to include Bsn to better reflect its use.

Preparation for new ingeschrevenpersonen endpoint

---

src/gobstuf/rest/brp/base_view.py
src/gobstuf/rest/brp/views.py
src/gobstuf/rest/routes.py
src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/tests/rest/brp/test_base_view.py
src/tests/stuf/brp/test_base_response.py

First version is the ability to find a person by postcode/huisnummer
Made some small changes to the base classes, but most new functionality is encapsulated in the StufRestFilterView class.
Changes in the existing code:
- StufRestView class has an added _validate method, plus some code is moved into methods so that they can be overridden. No functionality (besides the empty _validate method) is added.
- The BaseResponse class is able to return multiple objects now, using the already existing functionality.

PGB-1325 Add filter ingeschrevenpersonen endpoint to BRP API

---

src/gobstuf/rest/brp/base_view.py
src/gobstuf/rest/brp/views.py
src/tests/rest/brp/test_base_view.py

Adds the expand parameter to the brp endpoints. With this PR the expand parameter can be used in the IngeschrevenpersonenStufResponse.
The parameter is validated based on class-based settings.
Also added a technical assertion that the parent _validate() method is always called from the child class for the base views.

PGB-1238 Add expand parameter with validation to BRP Endpoints

---

src/gobstuf/rest/brp/views.py
src/gobstuf/stuf/brp/base_request.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/tests/stuf/brp/request/test_ingeschrevenpersonen.py

De BRP API is met het burgerservicenummer als path variabele gebouwd, echter deze dient ook als query parameter beschikbaar te zijn.

Accept burgerservicenummer parameter

---

src/gobstuf/rest/brp/base_view.py
src/gobstuf/rest/brp/views.py
src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
src/tests/rest/brp/test_base_view.py
src/tests/rest/brp/test_views.py

Some functions were moved to parent classes to allow for inheritance. The request now accepts ‘inclusiefoverledenpersonen’ as a functional query parameter.

Add functional parameter inclusiefoverledenpersonen

---

src/gobstuf/lib/communicatie.py
src/tests/lib/test_communicatie.py

When partner data is missing and naamgebruik != eigen
the the aanhef and aanschrijfwijze cannot be determined

Fix aanhef and aanschrijfwijze

---

src/gobstuf/lib/communicatie.py
src/tests/lib/test_communicatie.py

When partner data is missing and naamgebruik != eigen
the the aanhef and aanschrijfwijze cannot be bepaald

Release fix aanhef and aanschrijfwijze

---

src/gobstuf/lib/communicatie.py
src/tests/lib/test_communicatie.py

If the naamgebruik property is missing
aanhef and aanschrijfwijze are empty

Throw attribute error on missing naamgebruik

---

src/gobstuf/lib/communicatie.py
src/tests/lib/test_communicatie.py

If the naamgebruik property is missing
aanhef and aanschrijfwijze are empty

Release throw attribute error on missing naamgebruik

---

src/gobstuf/rest/brp/argument_checks.py
src/gobstuf/rest/brp/base_view.py
src/gobstuf/rest/brp/views.py
src/gobstuf/stuf/brp/base_request.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/gobstuf/stuf/message.py
src/tests/rest/brp/test_argument_checks.py
src/tests/rest/brp/test_base_view.py
src/tests/stuf/brp/request/test_ingeschrevenpersonen.py
src/tests/stuf/brp/test_base_request.py
src/tests/stuf/test_message.py

PGB-1241 Add Filtering on geslachtsnaam and geboortedatum to IngeschrevenPersonen endpoint.
Add convert functionality for StUF template for when the query parameter differs from the value expected by MKS.
Introduce a separate call to set_values when creating a request template; first validate the parameters, then set.
Print stacktrace on 500 from view.

Pgb 1241/brp geslachtsnaam geboortedatum

---

src/gobstuf/mks_utils.py
src/gobstuf/reference_data/code_resolver.py
src/gobstuf/rest/brp/argument_checks.py
src/gobstuf/rest/brp/views.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/tests/reference_data/test_code_resolver.py
src/tests/rest/brp/test_argument_checks.py
src/tests/stuf/brp/request/test_ingeschrevenpersonen.py
src/tests/test_mks_utils.py

A dictionary was added to be able to search on gemeente by omschrijving instead of code. This resulted in making the code resolver a bit more generic, by not only being able to lookup based on a 4 digit code. The fields were added to the parameter paths with a validation for gemeente.

Add option to search for straat, gemeente en huisnummer

---

src/gobstuf/rest/brp/base_view.py
src/gobstuf/rest/brp/views.py
src/gobstuf/rest/routes.py
src/gobstuf/stuf/brp/base_request.py
src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/gobstuf/stuf/brp/response/filters.py
src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
src/gobstuf/stuf/brp/response_mapping.py
src/tests/rest/brp/test_base_view.py
src/tests/rest/brp/test_views.py
src/tests/stuf/brp/test_base_response.py
src/tests/stuf/brp/test_response_mapping.py

New routes and views were added for the partner endpoints. The url parameters are now passed to the response template as well, since the partner_id is needed to filter the correct partner from the response object. Related Detail and List reponse types were added to allow for easy filtering on a specific embedded relation (in this case ‘partners’).

Add links and endpoints for partners

---

src/Dockerfile
src/gobstuf/stuf/brp/response_mapping.py

It is unclear if identificatiecodeAdresseerbaarObject is returned in the MKS response, it is currently mapped as specced, but the result will be empty for now. The subtask has been flagged.

Change response mapping for nummeraanduiding and adresseerbaarobject

---

src/gobstuf/rest/brp/argument_checks.py
src/gobstuf/rest/brp/base_view.py
src/gobstuf/stuf/brp/base_request.py
src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/message.py
src/tests/rest/brp/test_base_view.py
src/tests/stuf/brp/test_base_response.py

The filtering possible in MKS returns more results than expected. A wildcard filter has been added to filter the response objects to match the query

Filter MKS results using regex

---

src/gobstuf/rest/brp/base_view.py
src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/tests/stuf/brp/test_base_response.py

We needed an additional mapping to map url arguments to the response object

Only add the wildcard filter if a wildcard char is provided

---

src/gobstuf/stuf/brp/response_mapping.py

Fixed:
datumIngangGeldigheid can be an incomplete date 
nationaliteit should be nationaliteiten (https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/663)

Minor fixes for nationaliteit

---

src/deploy/docker-run.sh

Problems occur with infra upgrades. Every time after infra upgrade oauth2-proxy does not start.

Wait for keycloack to be reachable before starting oath2-proxy.

---

docker-compose.yml
src/test.sh

SECURE_SALT is not required, it is defined in docker however. Remove it, so that we do not need to configure it in OpenStack.

Remove SECURE_SALT, it is not required

---

src/gobstuf/mks_utils.py
src/tests/fixtures/response_310_nationaliteit_niet_geautoriseerd.xml
src/tests/rest/brp/test_views.py
src/tests/test_mks_utils.py

The response contained "nationaliteiten": [] when user had no permission. Now the key is entirely gone.

Remove nationaliteit when no permission is there

---

src/gobstuf/stuf/brp/request/ingeschrevenpersonen.py
src/tests/rest/brp/test_views.py

see: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/499
First check the length, if not valid raise this error. If valid check for digits.

Return correct error message when bsn is not valid

---

src/gobstuf/regression_tests/brp.py
src/tests/regression_tests/test_brp.py

get_object returns iterator instead of bytes
https://github.com/Amsterdam/GOB-Core/commit/d6bc469da5595d83b7361ec52d441fb1cce1f0ab

Fix writing objectstore objects

---

src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/brp/response/ingeschrevenpersonen.py
src/gobstuf/stuf/brp/response_mapping.py
src/tests/stuf/brp/test_base_response.py
src/tests/stuf/brp/test_response_mapping.py

A mapping can't only be derived from the entity type. A mapping can differ between different answer codes. 
Implemented a structure to hold the mappings per answer code.

Let response mapping depend on the answer code

---

src/gobstuf/rest/brp/base_view.py
src/gobstuf/rest/brp/views.py
src/gobstuf/stuf/brp/base_response.py
src/gobstuf/stuf/exception.py
src/tests/rest/brp/test_base_view.py
src/tests/stuf/brp/test_base_response.py

- Raise different exceptions based on if bsn is found or empty response due to filtering
- Handle exceptions seperately for both cases

Add `StufRestViewAsList` to return a list response from single object

---

src/gobstuf/regression_tests/brp.py

The removed routes in https://github.com/Amsterdam/GOB-StUF/pull/358 are still used in the regression tests leading to 404's.
Switch to HC_BASE_PATH env variable.

Use HC_BASE_PATH var in regression test

---

src/gobstuf/regression_tests/brp.py
src/tests/regression_tests/test_brp.py

Subtituting API_BASE_PATH let to double slashes in the url in case of empty string.

Fix substituting API_BASE_PATH in url
